[project]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Experiments in porting over Golang stdlib into Mojo."
name = "gojo"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.3.nightly"

[tasks]
tests = "bash scripts/tests.sh"
benchmarks = "bash scripts/benchmarks.sh"
package = "bash scripts/build.sh package"
build = "MODULAR_MOJO_NIGHTLY_IMPORT_PATH=$CONDA_PREFIX/lib/mojo rattler-build build -r src -c https://conda.modular.com/max-nightly -c conda-forge"

[dependencies]
max = ">=24.6.0.dev2024090605,<25"
