[project]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Experiments in porting over Golang stdlib into Mojo."
name = "gojo"
platforms = ["osx-arm64", "linux-64"]
version = "2024.1.0"
license = "MIT"
license-file = "LICENSE"
homepage = "https://github.com/thatstoasty/gojo"
repository = "https://github.com/thatstoasty/gojo"

[tasks]
run_file = "bash scripts/run_file.sh"
tests = "bash scripts/tests.sh"
benchmarks = "bash scripts/benchmarks.sh"
template = "magic run python scripts/templater.py"
build = { cmd = "bash scripts/build.sh", env = {MODULAR_MOJO_IMPORT_PATH = "$CONDA_PREFIX/lib/mojo"} }
publish = { cmd = "bash scripts/publish.sh", env = { PREFIX_API_KEY = "$PREFIX_API_KEY" } }
bp = { depends_on=["build", "publish"] }

[dependencies]
max = ">=24.5.0,<25"

[feature.nightly]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]

[feature.nightly.dependencies]
max = ">=24.6.0.dev2024101817"

[environments]
nightly = ["nightly"]
