[project]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Experiments in porting over Golang stdlib into Mojo."
name = "gojo"
platforms = ["osx-arm64"]
version = "0.1.3"

[tasks]
tests = "bash scripts/tests.sh"
benchmarks = "bash scripts/benchmarks.sh"
package = "bash scripts/build.sh package"
build = "MODULAR_MOJO_NIGHTLY_IMPORT_PATH=$CONDA_PREFIX/lib/mojo rattler-build build --no-include-recipe"

[dependencies]
max = ">=24.6.0.dev2024090405,<25"
