# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "13.4.2"

package:
  name: "gojo"
  version: 0.1.3

source:
  - path: ./src
  # - path: ./LICENSE

build:
  # files:
  #   - src/gojo/*.mojo
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - magic run mojo package gojo -o ${PREFIX}/lib/mojo/gojo.mojopkg

requirements:
  run:
    - max >= 24.6.0.dev2024090405

# tests:
#   - script:
#       # commands to run to test the package. If any of the commands
#       # returns with an error code, the test is considered failed.
#       - mojo test test/
#       - ls -la info/recipe
#       - cp ${PREFIX}/lib/mojo/gojo.mojopkg info/recipe/test/gojo.mojopkg
#       - mojo test info/recipe/test/

#     # requirements:
#     #   run:
#     #     - mojo

#     files:
#       # Extra files to be copied to the test directory from the "work directory"
#       source:
#         - ../src/
#         - ../test/

about:
  homepage: https://github.com/thatstoasty/gojo
  license: MIT
  license_file: LICENSE
  summary: Experiments in porting over Golang stdlib into Mojo. https://github.com/thatstoasty/gojo
  repository: https://github.com/thatstoasty/gojo
