# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "13.4.2"

package:
  name: "gojo"
  version: 0.1.12

source:
  - path: .
  - path: ../LICENSE
  - path: ../test

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - magic run mojo package gojo
    - cp gojo.mojopkg ${PREFIX}/lib/mojo/gojo.mojopkg

requirements:
  run:
    - max >= 24.5.0,<24.6.0

tests:
  - script:
      # commands to run to test the package. If any of the commands
      # returns with an error code, the test is considered failed.
      # if I don't copy everything into a test dir, mojo test runs the tests in the .magic dir and fails :|
      - mkdir -p test
      - mv test_*.mojo test/
      - mv data test/
      - mv gojo.mojopkg test/
      - magic run mojo test test

    files:
      # Extra files to be copied to the test directory from the "work directory"
      source:
        - gojo.mojopkg
        - mojoproject.toml
        - data/
        - test_*.mojo

about:
  homepage: https://github.com/thatstoasty/gojo
  license: MIT
  license_file: LICENSE
  summary: Experiments in porting over Golang stdlib into Mojo. https://github.com/thatstoasty/gojo
  repository: https://github.com/thatstoasty/gojo
